/// Operational action plan generated by Smart Explorer.
///
/// This is a non-sovereign planning artifact. It does not approve, mutate, or
/// commit data to waqf/core/gis source-of-truth tables.
class SmartExplorerActionPlan {
  const SmartExplorerActionPlan({
    required this.items,
    required this.generatedAt,
    required this.scopeLabelAr,
  });

  final List<SmartExplorerActionPlanItem> items;
  final DateTime generatedAt;
  final String scopeLabelAr;

  bool get isEmpty => items.isEmpty;
  int get totalItems => items.length;
  int get urgentItems => items.where((item) => item.priority >= 85).length;
  int get blockedItems => items.where((item) => item.status == SmartExplorerActionStatus.blocked).length;

  List<SmartExplorerActionPlanItem> get topItems {
    final out = List<SmartExplorerActionPlanItem>.from(items)
      ..sort((a, b) => b.priority.compareTo(a.priority));
    return out.take(20).toList(growable: false);
  }

  String get summaryAr {
    if (items.isEmpty) return 'لا توجد إجراءات تشغيلية ضمن النطاق الحالي.';
    return 'خطة إجراءات تضم $totalItems بندًا، منها $urgentItems عاجلة و$blockedItems مانعة.';
  }

  String toReportText() {
    final buffer = StringBuffer()
      ..writeln('خطة إجراءات المستكشف الذكي')
      ..writeln('النطاق: $scopeLabelAr')
      ..writeln('وقت التوليد: ${generatedAt.toIso8601String()}')
      ..writeln('الملخص: $summaryAr')
      ..writeln('تنبيه: الخطة تشغيلية غير سيادية ولا تعتمد أي تعديل بيانات.')
      ..writeln('---');
    for (final item in topItems) {
      buffer
        ..writeln('[${item.priorityLabelAr}] ${item.titleAr}')
        ..writeln('المجال: ${item.domainAr}')
        ..writeln('الحالة: ${item.status.labelAr}')
        ..writeln('المالك المقترح: ${item.ownerRoleAr}')
        ..writeln('الإجراء: ${item.actionAr}')
        ..writeln('الدليل المطلوب: ${item.requiredEvidenceAr}')
        ..writeln('معيار الإغلاق: ${item.acceptanceCriteriaAr}')
        ..writeln('---');
    }
    return buffer.toString();
  }
}

enum SmartExplorerActionStatus { ready, pendingEvidence, blocked, reviewOnly }

extension SmartExplorerActionStatusX on SmartExplorerActionStatus {
  String get labelAr {
    switch (this) {
      case SmartExplorerActionStatus.ready:
        return 'جاهز للتنفيذ';
      case SmartExplorerActionStatus.pendingEvidence:
        return 'بانتظار دليل';
      case SmartExplorerActionStatus.blocked:
        return 'مانع';
      case SmartExplorerActionStatus.reviewOnly:
        return 'مراجعة فقط';
    }
  }
}

class SmartExplorerActionPlanItem {
  const SmartExplorerActionPlanItem({
    required this.titleAr,
    required this.domainAr,
    required this.actionAr,
    required this.requiredEvidenceAr,
    required this.acceptanceCriteriaAr,
    required this.ownerRoleAr,
    required this.priority,
    required this.status,
    this.relatedResultId,
    this.relatedResultTitleAr,
  });

  final String titleAr;
  final String domainAr;
  final String actionAr;
  final String requiredEvidenceAr;
  final String acceptanceCriteriaAr;
  final String ownerRoleAr;
  final int priority;
  final SmartExplorerActionStatus status;
  final String? relatedResultId;
  final String? relatedResultTitleAr;

  String get priorityLabelAr {
    if (priority >= 85) return 'عاجل';
    if (priority >= 70) return 'عالٍ';
    if (priority >= 45) return 'متوسط';
    return 'منخفض';
  }
}
