import 'package:flutter/material.dart';

/// Non-sovereign review signal generated by Smart Explorer rules.
///
/// A signal is only an audit suggestion. It must never be treated as an
/// approved update to waqf_assets, endowments, parcels, or core reference data.
class SmartExplorerGapSignal {
  const SmartExplorerGapSignal({
    required this.code,
    required this.titleAr,
    required this.descriptionAr,
    required this.severity,
    required this.recommendedActionAr,
    this.icon = Icons.info_outline,
    this.weight = 1,
  });

  final String code;
  final String titleAr;
  final String descriptionAr;
  final SmartExplorerSignalSeverity severity;
  final String recommendedActionAr;
  final IconData icon;

  /// Optional scoring weight for review queues. It is local and non-sovereign.
  final int weight;

  bool get isCritical => severity == SmartExplorerSignalSeverity.critical;
  bool get isHigh => severity == SmartExplorerSignalSeverity.high;
  bool get isMedium => severity == SmartExplorerSignalSeverity.medium;
  bool get isLow => severity == SmartExplorerSignalSeverity.low;

  String get severityCode {
    switch (severity) {
      case SmartExplorerSignalSeverity.critical:
        return 'critical';
      case SmartExplorerSignalSeverity.high:
        return 'high';
      case SmartExplorerSignalSeverity.medium:
        return 'medium';
      case SmartExplorerSignalSeverity.low:
        return 'low';
    }
  }

  String get severityLabelAr {
    switch (severity) {
      case SmartExplorerSignalSeverity.critical:
        return 'حرجة';
      case SmartExplorerSignalSeverity.high:
        return 'عالية';
      case SmartExplorerSignalSeverity.medium:
        return 'متوسطة';
      case SmartExplorerSignalSeverity.low:
        return 'منخفضة';
    }
  }

  Color color(BuildContext context) {
    switch (severity) {
      case SmartExplorerSignalSeverity.critical:
        return const Color(0xFFB22222);
      case SmartExplorerSignalSeverity.high:
        return const Color(0xFFC77700);
      case SmartExplorerSignalSeverity.medium:
        return const Color(0xFF1D4ED8);
      case SmartExplorerSignalSeverity.low:
        return const Color(0xFF047857);
    }
  }
}

enum SmartExplorerSignalSeverity {
  low,
  medium,
  high,
  critical,
}
