/// Local review workflow generated by Smart Explorer.
///
/// This is a planning artifact only. It organizes human review and does not
/// write to any sovereign table.
class SmartExplorerReviewWorkflow {
  const SmartExplorerReviewWorkflow({
    required this.steps,
    required this.generatedAt,
    required this.scopeLabelAr,
  });

  final List<SmartExplorerReviewWorkflowStep> steps;
  final DateTime generatedAt;
  final String scopeLabelAr;

  bool get isEmpty => steps.isEmpty;
  int get totalSteps => steps.length;
  int get blockedSteps => steps.where((step) => step.status == SmartExplorerWorkflowStatus.blocked).length;
  int get readySteps => steps.where((step) => step.status == SmartExplorerWorkflowStatus.ready).length;

  String get summaryAr {
    if (steps.isEmpty) return 'لا توجد خطوات مراجعة قابلة للتوليد.';
    return 'مسار مراجعة يضم $totalSteps خطوات، منها $readySteps جاهزة و$blockedSteps مانعة.';
  }

  String toReportText() {
    final buffer = StringBuffer()
      ..writeln('مسار مراجعة المستكشف الذكي')
      ..writeln('النطاق: $scopeLabelAr')
      ..writeln('وقت التوليد: ${generatedAt.toIso8601String()}')
      ..writeln('الملخص: $summaryAr')
      ..writeln('تنبيه: المسار يوجه المراجعة البشرية فقط ولا يعتمد بيانات.')
      ..writeln('---');
    for (final step in steps) {
      buffer
        ..writeln('${step.order}. ${step.titleAr}')
        ..writeln('الحالة: ${step.status.labelAr}')
        ..writeln('المالك: ${step.ownerRoleAr}')
        ..writeln('المدخلات: ${step.inputAr}')
        ..writeln('المخرج: ${step.outputAr}')
        ..writeln('معيار الانتقال: ${step.exitCriteriaAr}')
        ..writeln('---');
    }
    return buffer.toString();
  }
}

enum SmartExplorerWorkflowStatus { ready, waitingInput, blocked, reviewOnly }

extension SmartExplorerWorkflowStatusX on SmartExplorerWorkflowStatus {
  String get labelAr {
    switch (this) {
      case SmartExplorerWorkflowStatus.ready:
        return 'جاهزة';
      case SmartExplorerWorkflowStatus.waitingInput:
        return 'بانتظار مدخلات';
      case SmartExplorerWorkflowStatus.blocked:
        return 'مانعة';
      case SmartExplorerWorkflowStatus.reviewOnly:
        return 'مراجعة فقط';
    }
  }
}

class SmartExplorerReviewWorkflowStep {
  const SmartExplorerReviewWorkflowStep({
    required this.order,
    required this.titleAr,
    required this.ownerRoleAr,
    required this.inputAr,
    required this.outputAr,
    required this.exitCriteriaAr,
    required this.status,
  });

  final int order;
  final String titleAr;
  final String ownerRoleAr;
  final String inputAr;
  final String outputAr;
  final String exitCriteriaAr;
  final SmartExplorerWorkflowStatus status;
}
