/// Operational work packages generated by Smart Explorer.
///
/// These packages are non-sovereign planning artifacts. They organize review,
/// field verification, data-governance, and history-analysis work without
/// approving or mutating source-of-truth records.
class SmartExplorerWorkPackageSet {
  const SmartExplorerWorkPackageSet({
    required this.packages,
    required this.generatedAt,
    required this.scopeLabelAr,
  });

  final List<SmartExplorerWorkPackage> packages;
  final DateTime generatedAt;
  final String scopeLabelAr;

  bool get isEmpty => packages.isEmpty;
  int get totalPackages => packages.length;
  int get urgentPackages => packages.where((item) => item.priority >= 85).length;
  int get totalActions => packages.fold<int>(0, (sum, item) => sum + item.actions.length);

  List<SmartExplorerWorkPackage> get topPackages {
    final out = List<SmartExplorerWorkPackage>.from(packages)
      ..sort((a, b) => b.priority.compareTo(a.priority));
    return out.take(12).toList(growable: false);
  }

  String get summaryAr {
    if (packages.isEmpty) return 'لا توجد حزم عمل ضمن النطاق الحالي.';
    return 'حزم عمل: $totalPackages، إجراءات: $totalActions، عاجلة: $urgentPackages.';
  }
}

class SmartExplorerWorkPackage {
  const SmartExplorerWorkPackage({
    required this.id,
    required this.titleAr,
    required this.objectiveAr,
    required this.domainAr,
    required this.priority,
    required this.actions,
    required this.expectedOutputAr,
    required this.acceptanceCriteria,
    this.relatedResultIds = const <String>[],
    this.ownerRoleAr = 'فريق التدقيق',
  });

  final String id;
  final String titleAr;
  final String objectiveAr;
  final String domainAr;
  final int priority;
  final List<String> actions;
  final String expectedOutputAr;
  final List<String> acceptanceCriteria;
  final List<String> relatedResultIds;
  final String ownerRoleAr;

  bool get isUrgent => priority >= 85;
  String get priorityLabelAr {
    if (priority >= 85) return 'عاجل';
    if (priority >= 70) return 'عالٍ';
    if (priority >= 45) return 'متوسط';
    return 'منخفض';
  }
}
