/// Field checklist generated by Smart Explorer for human review teams.
///
/// This checklist is local/non-sovereign. It helps organize verification work
/// and does not approve or mutate waqf/core records.
class SmartExplorerFieldChecklist {
  const SmartExplorerFieldChecklist({
    required this.items,
    required this.generatedAt,
    required this.scopeLabelAr,
  });

  final List<SmartExplorerFieldChecklistItem> items;
  final DateTime generatedAt;
  final String scopeLabelAr;

  bool get isEmpty => items.isEmpty;
  int get totalItems => items.length;
  int get urgentItems => items.where((item) => item.priority >= 85).length;
  int get photoRequiredCount => items.where((item) => item.requiresPhoto).length;
  int get documentRequiredCount => items.where((item) => item.requiresDocumentReview).length;

  List<SmartExplorerFieldChecklistItem> get topItems {
    final out = List<SmartExplorerFieldChecklistItem>.from(items)
      ..sort((a, b) => b.priority.compareTo(a.priority));
    return out.take(18).toList(growable: false);
  }

  String get summaryAr {
    if (items.isEmpty) return 'لا توجد بنود ميدانية ضمن النطاق الحالي.';
    return 'قائمة تدقيق تضم $totalItems بندًا، منها $urgentItems عاجلة، و$photoRequiredCount تحتاج صورة/دليلًا ميدانيًا.';
  }
}

class SmartExplorerFieldChecklistItem {
  const SmartExplorerFieldChecklistItem({
    required this.titleAr,
    required this.instructionAr,
    required this.evidenceRequiredAr,
    required this.domainAr,
    required this.priority,
    required this.locationLabelAr,
    this.resultId,
    this.resultTitleAr,
    this.assetCode,
    this.requiresPhoto = false,
    this.requiresDocumentReview = false,
  });

  final String titleAr;
  final String instructionAr;
  final String evidenceRequiredAr;
  final String domainAr;
  final int priority;
  final String locationLabelAr;
  final String? resultId;
  final String? resultTitleAr;
  final String? assetCode;
  final bool requiresPhoto;
  final bool requiresDocumentReview;

  bool get isUrgent => priority >= 85;

  String get priorityLabelAr {
    if (priority >= 85) return 'عاجل';
    if (priority >= 70) return 'عالٍ';
    if (priority >= 45) return 'متوسط';
    return 'منخفض';
  }
}
