/// Investigation-session workspace generated by Smart Explorer.
///
/// This model is a non-sovereign planning artifact. It describes where the
/// current smart-explorer workspace stands and what must happen next before any
/// information can be used by a sovereign system or formal report.
class SmartExplorerInvestigationSession {
  const SmartExplorerInvestigationSession({
    required this.sessionId,
    required this.scopeLabelAr,
    required this.generatedAt,
    required this.stages,
    required this.nextActionAr,
  });

  final String sessionId;
  final String scopeLabelAr;
  final DateTime generatedAt;
  final List<SmartExplorerInvestigationStage> stages;
  final String nextActionAr;

  bool get isEmpty => stages.isEmpty;
  int get totalStages => stages.length;
  int get blockedStages => stages.where((stage) => stage.status == SmartExplorerStageStatus.blocked).length;
  int get readyStages => stages.where((stage) => stage.status == SmartExplorerStageStatus.ready).length;
  int get activeStages => stages.where((stage) => stage.status == SmartExplorerStageStatus.active).length;

  String get summaryAr {
    if (stages.isEmpty) return 'لا توجد جلسة تحقيق مبنية بعد.';
    return 'جلسة تحقيق تضم $totalStages مراحل، جاهزة: $readyStages، نشطة: $activeStages، مانعة: $blockedStages.';
  }

  String toReportText() {
    final buffer = StringBuffer()
      ..writeln('جلسة تحقيق المستكشف الذكي')
      ..writeln('المعرف: $sessionId')
      ..writeln('النطاق: $scopeLabelAr')
      ..writeln('وقت التوليد: ${generatedAt.toIso8601String()}')
      ..writeln('الملخص: $summaryAr')
      ..writeln('الإجراء التالي: $nextActionAr')
      ..writeln('---');
    for (final stage in stages) {
      buffer
        ..writeln('[${stage.status.labelAr}] ${stage.titleAr}')
        ..writeln('المسؤول: ${stage.ownerRoleAr}')
        ..writeln('السبب: ${stage.reasonAr}')
        ..writeln('الإجراء: ${stage.nextActionAr}');
      if (stage.evidence.isNotEmpty) {
        buffer.writeln('الأدلة:');
        for (final item in stage.evidence.take(6)) {
          buffer.writeln('- $item');
        }
      }
      buffer.writeln('---');
    }
    return buffer.toString();
  }
}

enum SmartExplorerStageStatus { ready, active, blocked, pending }

extension SmartExplorerStageStatusX on SmartExplorerStageStatus {
  String get labelAr {
    switch (this) {
      case SmartExplorerStageStatus.ready:
        return 'جاهزة';
      case SmartExplorerStageStatus.active:
        return 'نشطة';
      case SmartExplorerStageStatus.blocked:
        return 'مانعة';
      case SmartExplorerStageStatus.pending:
        return 'بانتظار مدخلات';
    }
  }
}

class SmartExplorerInvestigationStage {
  const SmartExplorerInvestigationStage({
    required this.titleAr,
    required this.status,
    required this.ownerRoleAr,
    required this.reasonAr,
    required this.nextActionAr,
    this.evidence = const <String>[],
  });

  final String titleAr;
  final SmartExplorerStageStatus status;
  final String ownerRoleAr;
  final String reasonAr;
  final String nextActionAr;
  final List<String> evidence;
}
