/// A local, non-sovereign hypothesis generated by Smart Explorer.
///
/// This model is intentionally UI/review oriented. Persistence and approval
/// workflow remain controlled through Explorer Gap Audit Requests.
class SmartExplorerHypothesis {
  const SmartExplorerHypothesis({
    required this.id,
    required this.titleAr,
    required this.summaryAr,
    required this.confidence,
    required this.evidence,
    this.status = SmartExplorerHypothesisStatus.draft,
    this.intent = SmartExplorerHypothesisIntent.qualityReview,
    this.createdAt,
  });

  final String id;
  final String titleAr;
  final String summaryAr;
  final double confidence;
  final List<String> evidence;
  final SmartExplorerHypothesisStatus status;
  final SmartExplorerHypothesisIntent intent;
  final DateTime? createdAt;

  int get confidencePercent => (confidence.clamp(0, 1) * 100).round();

  String get statusLabelAr {
    switch (status) {
      case SmartExplorerHypothesisStatus.draft:
        return 'مسودة';
      case SmartExplorerHypothesisStatus.needsReview:
        return 'تحتاج مراجعة';
      case SmartExplorerHypothesisStatus.rejected:
        return 'مرفوضة';
      case SmartExplorerHypothesisStatus.approved:
        return 'معتمدة';
    }
  }

  String get intentLabelAr {
    switch (intent) {
      case SmartExplorerHypothesisIntent.spatialLinking:
        return 'ربط مكاني';
      case SmartExplorerHypothesisIntent.parcelMatching:
        return 'مطابقة قطع';
      case SmartExplorerHypothesisIntent.administrativeCompletion:
        return 'استكمال إداري';
      case SmartExplorerHypothesisIntent.endowmentReference:
        return 'ربط الوقف الأم';
      case SmartExplorerHypothesisIntent.historyLineage:
        return 'مراجعة تاريخية';
      case SmartExplorerHypothesisIntent.qualityReview:
        return 'تدقيق جودة';
    }
  }
}

enum SmartExplorerHypothesisStatus {
  draft,
  needsReview,
  rejected,
  approved,
}

enum SmartExplorerHypothesisIntent {
  spatialLinking,
  parcelMatching,
  administrativeCompletion,
  endowmentReference,
  historyLineage,
  qualityReview,
}
